#!/usr/bin/env bash
set -e

here="$(cd "${0%/*}"; pwd)"

echo "INSTALLING dotfiles ${here} => ${HOME}"
for file in "$here"/.[^.]*; do
  name="$(basename "$file")"

  if ! [[ "install README git" =~ $name || $name =~ ".plist" || -e ~/$name || -d $file/.git ]]; then
    echo " + $name"
    ln -sfh ${file} "${HOME}/${dotname}"
  else
    echo " - $name"
  fi
done
